### ISSUE TITLE
Descriptive Gate doesn't work with release builds

### ISSUE THREAD

**Issue by benjaminsavage** [private-attribution/ipa#1301]
Command:
`cargo run --release --no-default-features --features "multi-threading web-app real-world-infra stall-detection reveal-aggregation" --bin helper -- --identity $IDENTITY --network test_data/network.toml --port $((3000 + (IDENTITY - 1))) --disable-https`

Error:
```
error[E0277]: the trait bound `str: ipa_step::Step` is not satisfied
   --> ipa-core/src/query/executor.rs:217:58
    |
217 |     ipa_step::descriptive::Descriptive::default().narrow("prss")
    |                                                   ------ ^^^^^^ the trait `ipa_step::Step` is not implemented for `str`
    |                                                   |
    |                                                   required by a bound introduced by this call

```

**Comment by andyleiserson** [comment]
[This](https://github.com/private-attribution/ipa/blob/fbce8eca3a387b68ba4b0f657dfcab006f09ce55/ipa-core/Cargo.toml#L22) doesn't seem right to me. We want to disable, not enable, `string-step` in compact gate mode. But perhaps that's not even essential to the issue here, since this is about descriptive gate. I don't think you can specify features for other crates on the command line, so maybe add a new `descriptive-gate` feature that enables `ipa-step/string-step`?

**Comment by akoshelev** [comment]
yea I agree. This should've been the opposite I think
