### ISSUE TITLE
Channel-per-step for sending

### ISSUE THREAD

**Issue by martinthomson** [private-attribution/ipa#362]
Right now, all sending through the gateway goes through a single MPSC channel.  What I would like to move to is a separate sending structure for each `ChannelId` (i.e., `Step` + destination `Role`).  That means having a collection of these senders at the context layer.

The problem is that this relies on a context-wide structure.  We are currently creating channels on demand, so concurrent access will be challenging.  Ideally, accesses to this structure are cheap, but the process for creating new values will complicate that.  On the sending end, we need to ensure that multiple channels don't get created in parallel.  And on the receiving end of this channel, we need to spawn a task that will receive messages (see also #360).

Alex suggested that we could pre-generate channels from what we know about a protocol, which is a good idea that might build on the #139 nicely.  That might allow us to avoid more expensive structures and locking, just to access the channels.  We don't have to build that straight away though, because...

For tests. we'll need something a little more flexible.  For that, I was thinking that we put a `HashMap` at the context layer that is guarded with a `Mutex` and we could simply lock the structure and create the necessary objects as needed.

In doing this, I want to remove `Mesh`, or at least start to.  It doesn't add much value and a move to separate sending and receiving channels will make it cost more to invoke than we want (want to send left? you get a receiver as well, whether you want it or not).  A similar structure might be needed to encapsulate the sender's view of the channel, just as there might be a receiver object.  That means we'll end up with an API something like:

```rust
gateway.send_channel(role, step).send(message).await;
```

...which can be wrapped up by the context implementation.

We'll need a similar structure for receiving as well, I think, but let's do this one step at a time.  I think we are able to safely move sending without disturbing the receiving side too much.

(cc @andyleiserson and @akoshelev)

**Comment by andyleiserson** [comment]
I was also thinking about the locking issues for creating/obtaining channels yesterday. Since `gateway.mesh()` (or `send_channel` in your proposal) is in many cases called once for each record, it would be nice not to have to acquire a lock within that routine. I was also thinking about whether we can hold channel references in the context, but whether that solves the locking problem depends on whether use of the context is restricted to a single thread (or maybe whether the context is narrowed/cloned within the inner loop).

I agree that getting rid of `Mesh` makes sense, and that it makes sense to have a handle per (role, step) combination rather than a single object holding the channels to every helper for a given step. (e.g. the `to_left` / `to_right` members in https://github.com/andyleiserson/ipa/compare/context2...andyleiserson:ipa:context3?diff=split.)

**Comment by akoshelev** [comment]
I like this idea of having per-step+role channels exposed to the protocols. Ensuring that they've created once is a gnarly problem though :(

**Comment by akoshelev** [comment]
oh, this is fixed already in #532
