### ISSUE TITLE
Field trait cleanup

### ISSUE THREAD

**Issue by danielmasny** [private-attribution/ipa#812]
currently prss needs the field trait for the truncate function (i.e. generate a uniform value from a u128). This is counter intuitive since this has nothing to do with a mathematical field.

**Comment by akoshelev** [comment]
As part of this task, we probably should also fix the PRSS and let it generate a given number of bytes, rather than constraining it to 128 bits

**Comment by benjaminsavage** [comment]
Previously, there was a hack in the BooleanArray where the "try_from" and "truncate_from" functions would *hash* inputs rather than accepting the bits they were given.

I reverted this behavior in #853. This caused two tests to start failing (ABY share conversion and boolean_array_256 tests), so I disabled them.

Once this task is complete those tests should be re-enabled.

**Comment by danielmasny** [comment]
https://github.com/private-attribution/ipa/pull/868 fixes the issue with truncate and reenables the test. Truncate needs to be removed from PRSS. Truncate does not lead to a secure PRSS for BA256 and any secret sharing for values of more than 128 bit (unless we use hashing or a PRG within truncate).

**Comment by andyleiserson** [comment]
This is partially addressed (see the description of #877 for detail), but should remain open. I have marked some of the remaining cleanup with `TODO(812)` in the code.
