### ISSUE TITLE
Append counter to timestamps to avoid time collisions

### ISSUE THREAD

**Issue by richajaindce** [private-attribution/ipa#888]
OPRF involves a shuffle followed by a sort which can mess up the order of source and trigger events if they have the same timestamp value. 
@danielmasny and @martinthomson suggested we might preprocess records to extend timestamps with a counter to prevent collisions.
Until this is done, we will fallback to having unique timestamps per user for each test

**Comment by danielmasny** [comment]
This needs to be done just before calling the quicksort and it needs to be done on the secret shared timestamp (since we cannot trust the report collector to do this correctly to timestamps in the clear). Further, after appending the counter, We need to shuffle the records again.

**Comment by martinthomson** [comment]
Another shuffle would seem to negate a lot of the purported benefits of using quicksort here.  Is this truly quicker and easier than using a radix sort?

**Comment by benjaminsavage** [comment]
I'm less and less enthusiastic about quicksort. It doesn't produce a well known number of records - making it hard to square with our infra, and this need to append unique counters and re-shuffle really seems to make it less efficient than an even/odd mergesort.

**Comment by danielmasny** [comment]
Are there still any concerns after Ben's recent pushes? I am happy to consider other sorts but I think that quicksort works now pretty well with our infra.

**Comment by danielmasny** [comment]
A shuffle might actually not be necessary. It seems that just appending the counter (and trigger bit to make attributions consistent and independent of shuffle order) would be sufficient. The main reason is that we do not need to hide the counter, at the same time adding the counter only impacts outcomes between comparisons of identical timestamps and hence revealing it does not leak any information about the actual timestamp.

**Comment by danielmasny** [comment]
We actually do not even need to process the counter in MPC, we just compare them in the clear and feed the outcome as carry to MPC comparison circuit for the timestamp.

**Comment by martinthomson** [comment]
That would make things a lot simpler, I agree, especially if we don't have to extend the length of the compared field (which would add quite a bit to the cost).  Having to carry an additional counter with records isn't trivial, but a parallel array might work for this.  Essentially, we're forcing the algorithm to take the maximum number of comparisons relative to the original sorting.

Just to confirm: this ONLY works because the inputs are pre-shuffled, right?  That's probably worth capturing in documentation if it isn't already.

**Comment by danielmasny** [comment]
There is actually an easier solution that doesn't require a counter and it is easier to argue that it is secure. So instead of feeding the outcome of the comparisons of the two counters, we simple sample a random secret shared bit using PRSS and feed that as carry into the comparison. Since quicksort never compares the same two elements twice, it will be correct but an unstable sort since identical elements are arranged randomly. It should be secure, since the random bit could be the outcome of the comparison of two random nonces appended to the timestamp to make quicksort secure (using a counter or nonces works both fine as long as there are no collisions).

**Comment by danielmasny** [comment]
I didn't understand 

> Essentially, we're forcing the algorithm to take the maximum number of comparisons relative to the original sorting.

**Comment by benjaminsavage** [comment]
I am happy with the cost of our current shuffle now.![image](https://github.com/private-attribution/ipa/assets/52456851/8a7fe074-1cc9-4281-a952-c0f0ee4d174c)

It's not a big cost driver (at least when you've only got 10 rows per user...).

We can revisit this after optimizing the other stages.
